client_id = "58410467583-j5eq5bm4ali9qa5sbnagv1s8te9la4be.apps.googleusercontent.com"
client_secret = "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"
redirect_uri = "https://aib-2025-chronocall-q-01.streamlit.app/"